language: php
php:
  - '5.4'
  - '5.5'
  - '5.6'
services:
  - docker
before_install:
  - docker pull atmoz/sftp
  - docker run -v /host/share:/home/foo/share -p 2222:22 -d atmoz/sftp foo:123:1001
install:
  - composer install
script:
  - ./vendor/bin/phpunit --coverage-clover ./tests/logs/clover.xml
after_script:
  - php vendor/bin/coveralls -v
