language: php
php:
  - '5.4'
  - '5.5'
  - '5.6'
services:
  - docker
before_install:
  - (cd docker ; tar xpvzf docker.tar.gz)
  - docker pull rhasselbaum/scrappy-sftp
  - docker run -d --name sftp -p 2022:22 -v /$(pwd)/docker/sftp-root:/sftp-root -v /$(pwd)/docker/credentials:/creds rhasselbaum/scrappy-sftp
install:
  - composer install
script:
  - ./vendor/bin/phpunit --coverage-clover ./tests/logs/clover.xml
after_script:
  - php vendor/bin/coveralls -v

